// Generated by CoffeeScript 1.4.0
(function() {
  var xform,
    __hasProp = {}.hasOwnProperty;

  xform = function(code) {
    var $values, k, nextId, parsed, replace, transform, v, xformed;
    parsed = esprima.parse(code, {
      range: true
    });
    $values = {};
    nextId = 1;
    replace = function(e) {
      var id;
      if (e.type === 'Literal' && typeof e.value === 'number') {
        id = nextId++;
        $values[id] = {
          value: e.value,
          range: e.range
        };
        return {
          type: "MemberExpression",
          computed: true,
          object: {
            type: 'Identifier',
            name: '$values'
          },
          property: {
            type: 'Literal',
            value: '' + id
          }
        };
      } else {
        return transform(e, replace);
      }
    };
    transform = function(object, f) {
      var i, key, newObject, v, value, _i, _len;
      if (object instanceof Array) {
        newObject = [];
        for (i = _i = 0, _len = object.length; _i < _len; i = ++_i) {
          v = object[i];
          if (typeof v === 'object' && v !== null) {
            newObject[i] = f(v);
          } else {
            newObject[i] = v;
          }
        }
      } else {
        newObject = {};
        for (key in object) {
          if (!__hasProp.call(object, key)) continue;
          value = object[key];
          if (typeof value === 'object' && value !== null) {
            newObject[key] = f(value);
          } else {
            newObject[key] = value;
          }
        }
      }
      return newObject;
    };
    xformed = transform(parsed, replace);
    xformed.body.unshift({
      type: 'VariableDeclaration',
      declarations: [
        {
          type: 'VariableDeclarator',
          id: {
            type: 'Identifier',
            name: '$values'
          },
          init: {
            type: 'ObjectExpression',
            properties: (function() {
              var _results;
              _results = [];
              for (k in $values) {
                v = $values[k];
                _results.push({
                  type: 'Property',
                  key: {
                    type: 'Literal',
                    value: k
                  },
                  value: {
                    type: 'Literal',
                    value: v.value
                  },
                  kind: 'init'
                });
              }
              return _results;
            })()
          }
        }
      ],
      kind: 'var'
    });
    return {
      ast: xformed,
      values: $values
    };
  };

  window.xform = xform;

}).call(this);
